# Generated by Django 4.0.4 on 2024-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='resume',
            field=models.FileField(default=None, upload_to='pdf/'),
        ),
    ]
