# Generated by Django 4.0.4 on 2024-03-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victor', '0003_alter_home_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='resume',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
